name: My first workflow
on: 
   push: 
    branches: ["main"]
   workflow_dispatch:
  
jobs:
  bulid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Greet user
        run: echo welcome to github actions
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Greet user
        run: echo testing the code successfully
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Greet user
        run: echo deployment completed succesfully
